# Generated by Django 3.2.5 on 2021-07-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('posts', models.ManyToManyField(blank=True, null=True, to='post.Post')),
            ],
        ),
    ]
