version: "3.8"
   
services:
    django:
        build: .
        container_name: forum_api
        command: python manage.py runserver 
        volumes:
            - .:/code
            - /db.sqlite3
        ports:
            - "8000:8000"

           