# Generated by Django 3.2.5 on 2021-07-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentary', '0001_initial'),
        ('post', '0003_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentarys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentary.comentary'),
        ),
    ]
