# Generated by Django 3.2.5 on 2021-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentary', '0001_initial'),
        ('post', '0004_post_comentarys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentarys',
        ),
        migrations.AddField(
            model_name='post',
            name='comentarys',
            field=models.ManyToManyField(blank=True, to='comentary.Comentary'),
        ),
    ]
