# Generated by Django 3.2.5 on 2021-07-10 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comentary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentary',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
