# Generated by Django 3.2.5 on 2021-07-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentary', '0002_comentary_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentary',
            old_name='title',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='comentary',
            old_name='text',
            new_name='txt',
        ),
    ]
