# Generated by Django 3.2.5 on 2021-07-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentary', '0003_auto_20210710_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentary',
            name='head',
        ),
    ]
