# Generated by Django 3.2.5 on 2021-07-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentary', '0004_remove_comentary_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentary',
            old_name='txt',
            new_name='comment',
        ),
    ]
